artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF/view?usp=sharing
  local_data_file: artifacts/data_ingestion/card_transdata.csv
  unzip_dir: artifacts/data_ingestion



prepare_base_model:
  root_dir: artifacts/prepare_base_model




training:
  root_dir: artifacts/training
  model_save_filepath: artifacts/training/model.pkl
  local_data_file: artifacts/data_ingestion/card_transdata.csv



evaluation:
  model_save_filepath: artifacts/training/model.pkl
  local_data_file: artifacts/data_ingestion/card_transdata.csv



tracking:
  model_save_filepath: artifacts/training/model.pkl
  experiment_name: Default
  local_tracking_uri: /home/nair.ro/mlops-model-dev/notebooks/mlruns'
  remote_tracking_uri: https://dagshub.com/ronair212/mlops-model-dev.mlflow'
