name: Deploy to AWS S3

on:
  push:
    branches:
      - aws-s3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the pipeline
      run: python main.py

    - name: Upload CSV and model to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        aws s3 cp artifacts/data_ingestion/card_transdata.csv s3://$S3_BUCKET/card_transdata.csv
        aws s3 cp artifacts/training/model.pkl s3://$S3_BUCKET/model.pkl
