name: Deploy to EC2

on:
  push:
    branches:
      - aws-s3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PEM file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Create .env file
        env:
          AWS_S3_OBJECT_NAME: ${{ secrets.AWS_S3_OBJECT_NAME }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo "AWS_S3_OBJECT_NAME=${AWS_S3_OBJECT_NAME}" > .env
          echo "AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}" >> .env
          echo "AWS_SECRET_KEY=${AWS_SECRET_KEY}" >> .env
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
          cat .env

      - name: Copy .env file to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no .env $EC2_USER@$EC2_HOST:/home/ubuntu/.env

      - name: Deploy on EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            #!/bin/bash
            sudo su

            # Install Docker
            cd /home/ubuntu
            echo "Downloading Docker installation script..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            echo "Running Docker installation script..."
            sh get-docker.sh
            echo "Docker installation completed."

            # Install Docker Compose
            echo "Downloading Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            echo "Setting executable permissions for Docker Compose..."
            sudo chmod +x /usr/local/bin/docker-compose
            echo "Docker Compose installation completed."
            sudo docker system prune -f

            # Clone the repository
            cd /home/ubuntu
            rm -rf /home/ubuntu/mlops-model-dev
            echo "Cloning the mlops-model-dev repository..."
            git clone https://github.com/ronair212/mlops-model-dev.git
            echo "Repository cloned successfully."

            # Navigate into the repository directory
            cd /home/ubuntu/mlops-model-dev
            echo "Navigated into the mlops-model-dev directory."

            # Output the content of .env to verify
            echo "Verifying the content of thee .env file..."
            echo "Verification completed. Setup script finished."
            
            
            # Install Python dependencies if required
            echo "Installing Python dependencies..."
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install -r requirements.txt
            echo "Python dependencies installed."


            # Run your Python script
            echo "Running main.py..."
            python3 main.py
            echo "Python script executed successfully."
          EOF